services:
  app:
    image: maven:3.9.9-eclipse-temurin-21-alpine
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      sh -c "mvn clean package && java -jar target/valkiria-1.0.jar"
    ports:
      - '9090:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'